# {{str_to_sentence(dataset)}} Dataset

```{r data-{{dataset}}}
targets::tar_load(contains("{{dataset}}"))

ds_options_wDS <- 
  tribble(~label,                                ~opt,                    ~opt_nohlp,
          "Pass/fail measure",                   DS_Original_{{dataset}}, DS_Original_nohlp_{{dataset}},
          "1: Full composite",                   DS_Option1_{{dataset}},  DS_Option1_nohlp_{{dataset}},
          "2: Composite at criterion level",     DS_Option2_{{dataset}},  DS_Option2_nohlp_{{dataset}},
          "3: Composite at sub-criterion level", DS_Option3_{{dataset}},  DS_Option3_nohlp_{{dataset}},
          "4: Comparison of homogenous cells",   DS_Option4_{{dataset}},  DS_Option4_nohlp_{{dataset}},
          "4b: Algorithmic clustering",          DS_Option4b_{{dataset}}, DS_Option4b_nohlp_{{dataset}},
          "5: Classifier/regression-based",      DS_Option5_{{dataset}},  DS_Option5_nohlp_{{dataset}},
          "5b: Lasso classifier",                DS_Option5b_{{dataset}}, DS_Option5b_nohlp_{{dataset}})

ds_options <- ds_options_wDS %>% mutate(across(c(opt, opt_nohlp), ~map(., function(x) {select(x, -Durable_Solutions)})))

dict <- readxl::read_excel("Data/dict.xlsx", sheet = "{{dataset}}")
```

## Missingness plot

```{r naniar-{{dataset}}}
naniar::vis_miss(data_{{dataset}})
```

```{r missing-{{dataset}}}
combinations <- data_{{dataset}} %>% extract_indicators() %>% generate_combinations()

missing <- 
  1:nrow(combinations) %>% 
  map_dbl(~data_{{dataset}} %>% select(as.character(combinations[.x,])) %>% negate(complete.cases)() %>% mean()) %>% 
  enframe(name = NULL, value = "missing")

missing %>% 
  ggplot() + 
  geom_density(aes(missing)) +
  scale_x_continuous(labels = scales::label_percent()) +
  labs(title = "% of IDP cases with missing info",
       subtitle = "(based on different indicator combinations)") +
  theme_minimal()
```

## Density simulations

```{r density-{{dataset}}, fig.width=12, fig.height=12}
pmap(ds_options,
     ~ggplot(bind_rows("w/HLP" = ..2, "w/o HLP" = ..3, .id = "hlp"))+
       geom_density(aes(x = DS_perc, fill = hlp), alpha = 0.5)+
       geom_vline(aes(xintercept = mean_exited, color = hlp), 
                  linetype = "dashed", size = 1, # alpha = 0.5,
                  data = function(x) {x %>% group_by(hlp) %>% summarize(mean_exited = mean(DS_perc))})+
       scale_x_continuous(labels = scales::label_percent()) +
       theme_ipsum(plot_title_size = 13, base_size = 10)+
       labs(x = "Simulated proportion overcoming vulnerabilities", y = "Simulation density", 
            fill = NULL, color = NULL,
            title = ..1)) %>% 
  wrap_plots(ncol = 2) + plot_layout(guides = "collect") & theme(legend.position = "bottom")
```

## Indicators plot

```{r indicators-{{dataset}}, fig.width=8, fig.height=6}
indicator_hlp <-
  ds_options %>% 
  filter(!str_detect(label, "(3|5b):")) %>% 
  pull(opt) %>% 
  map(~lm(DS_perc*100 ~ .,
          data = select(., starts_with("I"), -any_of("iteration"), -where(~all(.==first(.))), DS_perc))) %>%
  map(broom::tidy, conf.int = TRUE) %>%
  bind_rows() %>%
  group_by(term) %>%
  summarize(across(c(estimate, conf.low, conf.high), mean)) %>%
  filter(term != "(Intercept)")

indicator_nohlp <-
  ds_options %>% 
  filter(!str_detect(label, "(3|5b):")) %>% 
  pull(opt) %>% 
  map(~lm(DS_perc*100 ~ .,
          data = select(., starts_with("I"), -any_of("iteration"), -where(~all(.==first(.))), DS_perc))) %>%
  map(broom::tidy, conf.int = TRUE) %>%
  bind_rows() %>%
  group_by(term) %>%
  summarize(across(c(estimate, conf.low, conf.high), mean)) %>%
  filter(term != "(Intercept)")

indicator_data <-
  bind_rows("w/ HLP" = indicator_hlp, "w/o HLP" = indicator_nohlp, .id = "hlp") %>%
  mutate(term = str_replace(term, "^(I\\d+)", "")) %>%
  left_join(dict, by = c(term = "variable")) %>%
  mutate(term1 = str_c(indicator, label, sep = ": ") %>% fct_rev())

ggplot(indicator_data,
       aes(x=term1, y=estimate)) +
  geom_hline(yintercept=0, colour="#8C2318", size=1) +  # Line at 0
  geom_pointrange(aes(ymin=conf.low, ymax=conf.high, color = hlp), position = position_dodge(1)) +
  labs(x="Indicator", y="Average effect estimate across metrices (in percentages of IDP stock)") +  # Labels
  # viridis::scale_color_viridis(discrete = TRUE)+
  # FIXME: what's the rational behind these magic constants?
  geom_rect(aes(ymin=0.4, ymax= 0.82, xmin=0, xmax=Inf),
            fill= "lightskyblue3",
            alpha = 0.01) +
  geom_rect(aes(ymin=-0.21, ymax= 0.23, xmin=0, xmax=Inf),
            fill= "lightskyblue4",
            alpha = 0.01) +
  geom_rect(aes(ymin=1.1, ymax= 1.43, xmin=0, xmax=Inf),
            fill= "lightskyblue",
            alpha = 0.01) +
  coord_flip() +  # Rotate the plot
  theme_ipsum(plot_title_size = 13, base_size = 10)+
  theme(legend.position = "bottom")
```

### Breakdown by Option

```{r indicators-options-{{dataset}}, fig.width=8, fig.height=30}
ds_options %>%
  filter(!str_detect(label, "(3|5b):")) %>% 
  pmap(~list("w/ HLP" = ..2, "w/o HLP" = ..3) %>%
         map(~lm(DS_perc*100 ~ .,
                 data = select(., starts_with("I"), -any_of("iteration"), -where(~all(.==first(.))), DS_perc))) %>%
         map(broom::tidy, conf.int = TRUE)) %>%
  map(~bind_rows(., .id = "hlp") %>%
        filter(term != "(Intercept)") %>%
        mutate(term = str_replace(term, "^(I\\d+)", "")) %>%
        left_join(dict, by = c(term = "variable")) %>%
        mutate(term1 = str_c(indicator, label, sep = ": ") %>% fct_rev())) %>%
  set_names(ds_options %>% filter(!str_detect(label, "(3|5b):")) %>% pull(label)) %>%
  imap(~ggplot(.x, aes(x=term1, y=estimate)) +
         geom_hline(yintercept=0, colour="#8C2318", size=1) +  # Line at 0
         geom_pointrange(aes(ymin=conf.low, ymax=conf.high, color = hlp), position = position_dodge(1)) +
         labs(x="Indicator", y="Average effect estimate across metrices (in percentages of IDP stock)",
              title = .y) +  # Labels
         # FIXME: what's the rational behind these magic constants?
         geom_rect(aes(ymin=0.4, ymax= 0.82, xmin=0, xmax=Inf),
                   fill= "lightskyblue3", alpha = 0.01) +
         geom_rect(aes(ymin=-0.21, ymax= 0.23, xmin=0, xmax=Inf),
                   fill= "lightskyblue4", alpha = 0.01) +
         geom_rect(aes(ymin=1.1, ymax= 1.43, xmin=0, xmax=Inf),
                   fill= "lightskyblue", alpha = 0.01) +
         coord_flip() +  # Rotate the plot
         theme_ipsum(plot_title_size = 13, base_size = 10)+
         theme(legend.position = "bottom")) %>%
  wrap_plots(ncol = 1) + plot_layout(guides = "collect") & theme(legend.position = "bottom")
```

## Inter-rater Agreement

```{r irr-hlp-{{dataset}}, fig.width=12, fig.height=12}
combined_results <- 
  ds_options_wDS %>% 
  filter(!str_detect(label, "^(3|5b):")) %>% 
  { set_names(.$opt, .$label) } %>% 
  bind_rows(.id = "metric") %>% 
  mutate(across(cell_1:cell_3, ~str_replace(., "HH_", "")),
         metric = if_else(!is.na(cell_1), glue::glue("{metric} ({cell_1},{cell_2},{cell_3})"), metric)) %>% 
  select(-DS, -DS_perc, -(cell_1:cell_3)) %>% 
  unnest(Durable_Solutions) %>%
  mutate(exited = as_factor(exited)) %>%
  pivot_wider(names_from = "metric", values_from = "exited")

nms <- combined_results %>% select(!!(ds_options_wDS$label[[1]]):last_col()) %>% names() %>% as_factor()

metric_pairs <-
  cross_df(list(x = nms, y = fct_rev(nms))) %>%
  filter((row_number() - 1) %>% {. %/% length(nms) > . %% length(nms)}) %>%
  mutate(kappa = map2_dbl(x, y, ~yardstick::kap_vec(combined_results[[.x]], combined_results[[.y]])))

metric_pairs %>% 
  ggplot() + 
  geom_tile(aes(x, y, fill = kappa), color = "grey50") + 
  scale_y_discrete(label = function(x) {str_replace(x, " \\(", "\n\\(")}) +
  scale_x_discrete(label = function(x) {str_replace(x, " \\(", "\n\\(")},
                   guide = guide_axis(angle = 90),
                   position = "top") + 
  scale_fill_steps() +
  labs(x = NULL, y = NULL, title = "Inter-rater Agreement", subtitle = "w/HLP indicators") +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r ira-nohlp-{{dataset}}, fig.width=12, fig.height=12}
combined_results <- 
  ds_options_wDS %>% 
  filter(!str_detect(label, "^(3|5b):")) %>% 
  { set_names(.$opt_nohlp, .$label) } %>% 
  bind_rows(.id = "metric") %>% 
  mutate(across(cell_1:cell_3, ~str_replace(., "HH_", "")),
         metric = if_else(!is.na(cell_1), glue::glue("{metric} ({cell_1},{cell_2},{cell_3})"), metric)) %>% 
  select(-DS, -DS_perc, -(cell_1:cell_3)) %>% 
  unnest(Durable_Solutions) %>%
  mutate(exited = as_factor(exited)) %>%
  pivot_wider(names_from = "metric", values_from = "exited")

nms <- combined_results %>% select(!!(ds_options_wDS$label[[1]]):last_col()) %>% names() %>% as_factor()

metric_pairs <-
  cross_df(list(x = nms, y = fct_rev(nms))) %>%
  filter((row_number() - 1) %>% {. %/% length(nms) > . %% length(nms)}) %>%
  mutate(kappa = map2_dbl(x, y, ~yardstick::kap_vec(combined_results[[.x]], combined_results[[.y]])))

metric_pairs %>% 
  ggplot() + 
  geom_tile(aes(x, y, fill = kappa), color = "grey50") + 
  scale_y_discrete(label = function(x) {str_replace(x, " \\(", "\n\\(")}) +
  scale_x_discrete(label = function(x) {str_replace(x, " \\(", "\n\\(")},
                   guide = guide_axis(angle = 90),
                   position = "top") + 
  scale_fill_steps() +
  labs(x = NULL, y = NULL, title = "Inter-rater Agreement", subtitle = "w/o HLP indicators") +
  theme_minimal() +
  theme(legend.position = "bottom")
```
