#' @title Hargeisa
#' @description Hargeisa
#' @format A data frame with 13065 rows and 180 variables:
#' \describe{
#'   \item{\code{hargeisa1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa5}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa6}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa7}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa8}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa11}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa12}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa13}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa15}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa16}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa17}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa18}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa19}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa20}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa21}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa22}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa23}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa24}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa25}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa26}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa27}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa29}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa30}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa31}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa32}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa33}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa34}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa35}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa36}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa37}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa38}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa39}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa40}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa41}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa42}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa43}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa44}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa45}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa46}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa47}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa48}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa49}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa50}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa51}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa52}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa53}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa54}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa55}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa56}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa57}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa58}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa59}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa60}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa61}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa62}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa63}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa64}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa65}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa66}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa67}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa68}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa69}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa70}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa71}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa72}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa73}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa74}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa75}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa76}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa77}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa78}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa79}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa80}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa81}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa82}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa83}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa84}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa85}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa86}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa87}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa88}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa89}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa90}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa91}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa92}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa93}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa94}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa95}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa96}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa97}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa98}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa99}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa100}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa101}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa102}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa103}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa104}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa105}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa106}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa107}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa108}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa109}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa110}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa111}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa112}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa113}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa114}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa115}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa116}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa117}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa118}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa119}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa120}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa121}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa122}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa123}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa124}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa125}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa126}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa127}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa128}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa129}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa130}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa131}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa132}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa133}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa134}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa135}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa136}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa137}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa138}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa139}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa140}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa141}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa142}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa143}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa144}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa145}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa146}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa147}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa148}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa149}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa150}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa151}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa152}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa153}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa154}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa155}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa156}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa157}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa158}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa159}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa160}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa161}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa162}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa163}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa164}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa165}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa166}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa167}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa168}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa169}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa170}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa171}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa172}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa173}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa174}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa175}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa176}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa177}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa178}}{character COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa179}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hargeisa180}}{double COLUMN_DESCRIPTION} 
#'}
#' @source \url{http://somewhere.important.com/}
"hargeisa"



#' @title Nigeria
#' @description DATASET_DESCRIPTION
#' @format A data frame with 2947 rows and 603 variables:
#' \describe{
#'   \item{\code{region}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ea}}{double COLUMN_DESCRIPTION}
#'   \item{\code{migr_idp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hh}}{double COLUMN_DESCRIPTION}
#'   \item{\code{enum}}{double COLUMN_DESCRIPTION}
#'   \item{\code{month}}{character COLUMN_DESCRIPTION}
#'   \item{\code{plinePPP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{poorPPP_prob}}{double COLUMN_DESCRIPTION}
#'   \item{\code{poor}}{double COLUMN_DESCRIPTION}
#'   \item{\code{pline125PPP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{poor125PPP_prob}}{double COLUMN_DESCRIPTION}
#'   \item{\code{poor125}}{double COLUMN_DESCRIPTION}
#'   \item{\code{pline31PPP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{poor31PPP_prob}}{double COLUMN_DESCRIPTION}
#'   \item{\code{poor31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hhh_id}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A_1_1_my_date}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A_1_6_migr_disp_past}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_1_2_hhr_id}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_1_4_hhh_presence}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_9_1_hhm_separated}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_1_disp_hhm_otherloc1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_1_disp_hhm_spec1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B_10_2_hhm_unite_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Beginning_datetime_b}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Behavioural_beh_treat_opt}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_1_housingtype}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_2_rooms_n}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_2_rooms_n_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_3_slrooms_n}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_7_tenure}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_7_tenure_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_1_8_land_own_dur_n_main}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_9_land_legal_main}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_10_land_legal_main_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_11_water_home}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_11_water_home_ot}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_1_12_cook_source_ot}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_1_12_water_home2}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{twater_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{twater_h}}{double COLUMN_DESCRIPTION}
#'   \item{\code{twater_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{twater_m}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_14_water_obstacle}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_14_water_obstacle_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_1_15_who_fetch}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_method_treat_ot}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_1_16_treat_water}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_17_light}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_17_light_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_1_18_electricity_phone}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_19_electricity_hours}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_19_electricity_hours_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_20_cook}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_20_cook_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_1_21_toilet}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_21_toilet_ot}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_1_22_share_facility}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_24_waste}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_24_waste_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{tmarket_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tmarket_h}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tmarket_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tmarket_m}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tedu_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tedu_h}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tedu_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tedu_m}}{double COLUMN_DESCRIPTION}
#'   \item{\code{thealth_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{thealth_h}}{double COLUMN_DESCRIPTION}
#'   \item{\code{thealth_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{thealth_m}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tpolice_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tpolice_h}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tpolice_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tpolice_m}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_29_phone_network}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_30_acc_int}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_1_31_acc_road}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_1_housingtype_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_2_rooms_n_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_2_rooms_n_disp_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_3_slrooms_n_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_4_tenure_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_4_tenure_disp_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_2_5_land_own_n_main_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_6_land_legal_main_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_7_land_legal_main_disp_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_8_land_use_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_8_land_use_disp_s}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_2_9_land_res_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_10_land_help_disp}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{C_2_10_land_help_disp_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_2_11_land_res_r_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_11_land_res_r_disp_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_2_12_land_back_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_13_water_home_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_13_water_home_ot_disp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_2_14_water_home2_disp}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{C_2_14_water_home2_ot_disp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{twater_d_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{twater_d_disp_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{twater_h_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{twater_m_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tmarket_d_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tmarket_d_disp_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tmarket_h_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tmarket_m_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tedu_d_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tedu_d_disp_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tedu_h_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tedu_m_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{thealth_d_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{thealth_d_disp_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{thealth_h_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{thealth_m_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_19_light_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_20_toilet_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_20_toilet_ot_disp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_2_21_waste_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_2_21_waste_disp_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{tpolice_d_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tpolice_h_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tpolice_kdk_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tpolice_m_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_1_land_access_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_2_land_access}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_2_land_access_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_3_land_unit}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_3_land_unit_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_3_4_land_tenure}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_4_land_tenure_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_3_5_land_own_dur_n}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_6_land_legal}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_7_land_legal_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_8_land_access_change}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_9_land_access_yn_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_10_land_access_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_10_land_access_disp_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_11_land_unit_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_11_land_unit_spec_disp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_3_12_land_tenure_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_12_land_tenure_ot_disp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_3_13_land_own_dur_n_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_14_land_legal_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_15_land_legal_d_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_16_land_lost_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_17_landag_use_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_3_17_landag_use_disp_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_4_1_nomoney}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_2_cop_lessprefrerred}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_3_cop_borrow_food}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_4_cop_limitportion}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_5_cop_limitadult}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_6_cop_reducemeals}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_7_cop_sellassets}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_8_cop_sellfem}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_9_cop_borrow}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_10_disease_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_11_disease_sev}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_12_med_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_13_med_no_y}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_14_med_no_y_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_4_15_bank_account}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_16_acc_mobile_money}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_17_social_saf_net}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_17_social_saf_net_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_4_18_social_ease}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_20_social_net_leader}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_21_particpate}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_4_22_social_net}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_1_lhood}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_1_lhood_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_2_assist_source_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_5_3_cash_assist}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_3_cash_assist_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_4_lhood_prev}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_4_lhood_prev_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_5_4_obs_access_aid}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_4_obs_access_aid_g}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_4_obs_access_aid_g_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_5_4_obs_access_aid_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_5_5_intremit_relation}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_5_intremit_relation_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_5_6_intremit_source}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_7_intremit_source_mig}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_8_intremit_mode_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C_5_9_intremit_freq}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_10_intremit_prev_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_11_intremit_moreless}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_12_supp_nig_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_13_supp_nig_prev_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_5_14_supp_moreless}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C_22_share_num}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D_1_1_last_meal}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D_1_2_last_bread}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D_1_5_last_p}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D_1_7_last_m}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D_1_9_last_f}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D_1_okay_lie_n}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Does_hhh_name_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{End_datetime_e}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Errors_has__errors}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_1_1_hhr_same}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_1_satisf_life}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_2_satisf_prev}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_3_agree_satisfied}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_4_rate_personal}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_5_rate_personal_future}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_6_health_satisfaction}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_6_market_satisfaction}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_7_school_satisfaction}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_8_empl_satisfaction}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_9_legal_id_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_10_legal_id_acc_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_10_obst_id}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_11_legal_access_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_12_compare_neighbreelate}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_13_compare_relate_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_14_idp_relations}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_15_idp_support}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_17_idp_relations2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_18_idp_jobs}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_19_idp_sec}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_2_20_idp_access}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_1_move_free}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_1_safe_violence}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_2_safe_walking_night}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_3_safe_walking_day}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_4_dispute_resolve}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_5_dispute_resolve_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H_4_6_report_access}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_7_report_challenge}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_8_report_chellenge_d_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H_4_9__dispute_r_p_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H_4_9_dispute_resolve_police}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_10_effective_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_11_conf_nonphys_harm__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H_4_12_report_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_1_disp_from}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_2_disp_from_region}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_2_disp_from_region_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_1_3_disp_date}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_4_disp_reason_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_1_5_disp_site}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_5_disp_site_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_6_disp_site_reason}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_6_disp_site_reason_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_1_7_disp_arrive_date}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_8_disp_arrive_r_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_1_10_disp_hhm_contact}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_11_disp_temp_return}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_12_disp_temp_kdk}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_12_disp_temp_return_n}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_13_disp_temp_return_r}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_13_disp_temp_return_r_s}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_1_13_stay_org}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_14_disp_comm_loc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_15_disp_shelterpay}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_18_disp_shpay_what_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_1_move_want}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_1_move_want_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_2_concrete_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_2_move_want_time}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_3_move_to_loc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_4_attend_consult}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_5_consult_time}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_6_consult_org}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_7_move_no_push_main__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_7_move_no_push_main__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_7_move_no_push_main__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_7_move_no_push_main__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_7_move_no_push_main__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_7_move_no_push_main__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_7_move_no_push_main__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_7_move_no_push_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_main__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_8_move_no_pull_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_main__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_9_move_yes_push_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_10_move_no_org_main_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_11_move_yes_pull_main__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_11_move_yes_pull_main__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_11_move_yes_pull_main__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_11_move_yes_pull_main__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_11_move_yes_pull_main__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_11_move_yes_pull_main__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_11_move_yes_pull_main__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_11_move_yes_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_12_obst_move}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_12_obst_move_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_13_move_help_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_14_security}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_15_sec_challenges}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_2_15_sec_challenges_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_2_16_sec_transit}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_1_inf_source}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_1_inf_source_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_3_2_inf_source_more}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_3_inf_source_add__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_4_inf_source_add_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_3_5_inf_comp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_6_inf_want__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_3_7_inf_want_sp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I_4_1_disp_from_r}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_4_2_disp_date_r}}{character COLUMN_DESCRIPTION}
#'   \item{\code{J_1_1_contact_phone_yn}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J_1_2_contact_phone_share}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_1_success_interview}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_2_same_respondent}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_3_respondent_name}}{character COLUMN_DESCRIPTION}
#'   \item{\code{K_1_4_privacy}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_5_privacy_external}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_6_respondent_multi}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_7_respondent_attitude}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_8_respondent_q}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K_1_9_respondent_q_section__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Please_hhr_id_perc}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Replacement_replacement_rank}}{double COLUMN_DESCRIPTION}
#'   \item{\code{_cook_str}}{character COLUMN_DESCRIPTION}
#'   \item{\code{_datetime_c}}{character COLUMN_DESCRIPTION}
#'   \item{\code{_electricity_str}}{character COLUMN_DESCRIPTION}
#'   \item{\code{_hhh_id0_int}}{double COLUMN_DESCRIPTION}
#'   \item{\code{_hhh_id1_int}}{double COLUMN_DESCRIPTION}
#'   \item{\code{_int_num_final}}{double COLUMN_DESCRIPTION}
#'   \item{\code{_interview__status}}{character COLUMN_DESCRIPTION}
#'   \item{\code{_mod_opt_check}}{double COLUMN_DESCRIPTION}
#'   \item{\code{_nhhm}}{double COLUMN_DESCRIPTION}
#'   \item{\code{_success}}{double COLUMN_DESCRIPTION}
#'   \item{\code{camp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hhsize}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hhsize_pre}}{double COLUMN_DESCRIPTION}
#'   \item{\code{lga}}{character COLUMN_DESCRIPTION}
#'   \item{\code{mod_hh}}{double COLUMN_DESCRIPTION}
#'   \item{\code{replacement_hh}}{double COLUMN_DESCRIPTION}
#'   \item{\code{return_live}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_r__1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_r__2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_r__3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_r__4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_r__1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_r__n98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_r__n99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_r_spec}}{character COLUMN_DESCRIPTION}
#'   \item{\code{returnee_resettle}}{double COLUMN_DESCRIPTION}
#'   \item{\code{returnee_v}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ward}}{character COLUMN_DESCRIPTION}
#'   \item{\code{weight}}{double COLUMN_DESCRIPTION}
#'   \item{\code{house}}{double COLUMN_DESCRIPTION}
#'   \item{\code{house_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I_1_16_disp_shpay_who__6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hhdensity}}{double COLUMN_DESCRIPTION}
#'   \item{\code{memperroom}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hhdensity_pre}}{double COLUMN_DESCRIPTION}
#'   \item{\code{memperroom_pre}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hhdensity_sl}}{double COLUMN_DESCRIPTION}
#'   \item{\code{memperroom_sl}}{double COLUMN_DESCRIPTION}
#'   \item{\code{hhdensity_sl_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{memperroom_sl_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tenure}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tenure_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{watersource}}{double COLUMN_DESCRIPTION}
#'   \item{\code{watersource2}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{watersource_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{watersource_disp2}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{time_market_min}}{double COLUMN_DESCRIPTION}
#'   \item{\code{markettime}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_edu_min}}{double COLUMN_DESCRIPTION}
#'   \item{\code{edutime}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_health_min}}{double COLUMN_DESCRIPTION}
#'   \item{\code{healthtime}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_water_min}}{double COLUMN_DESCRIPTION}
#'   \item{\code{watertime}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_police_min}}{double COLUMN_DESCRIPTION}
#'   \item{\code{policetime}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_market_min_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{markettime_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_edu_min_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{edutime_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_health_min_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{healthtime_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_water_min_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{watertime_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{time_police_min_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{policetime_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{cooking}}{double COLUMN_DESCRIPTION}
#'   \item{\code{sanitation}}{double COLUMN_DESCRIPTION}
#'   \item{\code{sanitation_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{lighting}}{double COLUMN_DESCRIPTION}
#'   \item{\code{who_fetch}}{double COLUMN_DESCRIPTION}
#'   \item{\code{lighting_disp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{csi}}{double COLUMN_DESCRIPTION}
#'   \item{\code{csi_cat}}{double COLUMN_DESCRIPTION}
#'   \item{\code{share_num_new}}{double COLUMN_DESCRIPTION}
#'   \item{\code{year}}{double COLUMN_DESCRIPTION}
#'   \item{\code{month_disp}}{character COLUMN_DESCRIPTION}
#'   \item{\code{day}}{character COLUMN_DESCRIPTION}
#'   \item{\code{displacementdate}}{character COLUMN_DESCRIPTION}
#'   \item{\code{disp_times}}{double COLUMN_DESCRIPTION}
#'   \item{\code{year_arrival}}{double COLUMN_DESCRIPTION}
#'   \item{\code{asset_index_current}}{double COLUMN_DESCRIPTION}
#'   \item{\code{food_cons_defl}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tc_core}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tc_summ}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tc_imp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{mi_cons_d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{mi_cons_f}}{double COLUMN_DESCRIPTION}
#'   \item{\code{mi_cons_nf}}{double COLUMN_DESCRIPTION}
#'   \item{\code{cons_f}}{double COLUMN_DESCRIPTION}
#'   \item{\code{cons_nf}}{double COLUMN_DESCRIPTION}
#'   \item{\code{quintiles_tc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{depend_share}}{double COLUMN_DESCRIPTION} 
#'}
#' @source \url{http://somewhere.important.com/}
"nigeria"